// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"
)

type Post struct {
	ID           int64          `json:"id"`
	UserID       int64          `json:"userID"`
	Description  sql.NullString `json:"description"`
	Uri          string         `json:"uri"`
	IsActive     bool           `json:"isActive"`
	CreatedAt    time.Time      `json:"createdAt"`
	UpdatedAt    time.Time      `json:"updatedAt"`
	ThumbnailUri sql.NullString `json:"thumbnailUri"`
	Blob         []byte         `json:"blob"`
}

type User struct {
	ID        int64          `json:"id"`
	FirstName string         `json:"firstName"`
	LastName  string         `json:"lastName"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	AvatarUri sql.NullString `json:"avatarUri"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
	Ts        interface{}    `json:"ts"`
}
