BEGIN;

CREATE TABLE posts(
	id BIGSERIAL PRIMARY KEY,
	user_id BIGSERIAL REFERENCES users (id) ON DELETE CASCADE NOT NULL,
	description TEXT,
	uri VARCHAR(255) NOT NULL,
	is_active Boolean NOT NULL DEFAULT TRUE,
	email VARCHAR(255) UNIQUE NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

COMMIT;