version: '3'

services:
  postgres:
    image: postgres:12.5-alpine
    container_name: tik_tok_pg
    env_file:
      - ./config/docker.env
    ports:
      - '5432:5432'
  redis:
    container_name: tik_tok_redis
    image: redis:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '6379:6379'
